recipe: default.v1

language: ar

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 3
  max_ngram: 5
- name: DIETClassifier
  epochs: 100
- name: FallbackClassifier
  threshold: 0.70
  ambiguity_threshold: 0.10

policies:
- name: RulePolicy
assistant_id: 20260407-210124-dynamic-burgundy
